"""
Django settings for pricematchguru project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _


os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l6hg+$-3h0dp@0#+0+30$f79-o+^9k&(l$z5=ig-lzaav#lw12'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# True

ALLOWED_HOSTS = ["127.0.0.1", "localhost","*","introprepai.onrender.com"]

# Whitenoise settings (for better caching)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"




LANGUAGES = [
    ('en', _('English')),
    ('hi', _('Hindi')),
    ('fr', _('French')),
    ('es', _('Spanish')),
    ('de', _('German')),
    ('zh-hans', _('Chinese (Simplified)')),
    ('ru', _('Russian')),
    ('ar', _('Arabic')),
    ('it', _('Italian')),
    ('pt', _('Portuguese')),
    ('ja', _('Japanese')),
    ('ko', _('Korean')),
    ('tr', _('Turkish')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
    ('mr', _('Marathi')),
    ('gu', _('Gujarati')),
    ('ur', _('Urdu')),
    ('bn', _('Bengali')),
    ('ml', _('Malayalam')),
]


LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

USE_I18N = True
USE_L10N = True


# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'django_browser_reload',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Added
     "django_browser_reload.middleware.BrowserReloadMiddleware", #aded
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware', #added
]

ROOT_URLCONF = 'pricematchguru.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [   BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'theme.context_processors.theme',  # Added
                'django.template.context_processors.i18n',  # Required for translations
                'home.language_context_processor.languages_context',  # Add your context processor here
            ],
        },
    },
]

WSGI_APPLICATION = 'pricematchguru.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

INTERNAL_IPS = [
    "127.0.0.1",
]





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Set the directory where collected static files will be stored


STATIC_URL = '/static/'

# Added
STATICFILES_DIRS = [
    BASE_DIR / "static",
    
]
STATIC_ROOT = BASE_DIR / "staticfiles" 

# Set the directory where Django will look for additional static files
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'  # Redirect unauthorized users to login page
TAILWIND_APP_NAME = 'theme'  # define the app name for tailwind to work
NPM_BIN_PATH = 'C:/Program Files/nodejs/npm.cmd'  # define the path to npm


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# email

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # If using Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "akhileshpandey878889@gmail.com"  # Change this
EMAIL_HOST_PASSWORD = "eipp poph qmaw gyuh"  # Use App Password if 2FA enabled

DEFAULT_FROM_EMAIL = 'akhileshpandey878889@gmail.com'
CONTACT_RECEIVER_EMAIL = 'akhileshpandey878889@gmail.com'



# Forgot password settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'akhileshpandey878889@gmail.com'         # Replace with your Gmail
EMAIL_HOST_PASSWORD = 'dvgv pqol hyne apfr'        # Use the App Password generated
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
