# Generated by Django 5.1.6 on 2025-02-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_imageupload_user_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='user',
        ),
    ]
